name: swapi # you probably want to 'snapcraft register <name>'
version: '0.1+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Star wars rest api showcase # 79 char long summary
description: |
  This is a showcase for REST api with CRSD operations for Star Wars Planets

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  swapi:
    command: swapi
    plugs: [home, network, network-bind]

parts:
  swapi:
    source: .
    plugin: rust
    rust-revision: nightly-2018-05-10
    stage-packages:
      - g++
      - make
      - pkg-config
      - libssl-dev
      - libsqlite3-dev